import { HumanMessage } from "@langchain/core/messages";
import { StateSchema, MessagesValue,type GraphNode, ReducedValue, StateGraph, START, END } from "@langchain/langgraph";
import {z} from 'zod'
import { cohereModel, geminiModel, mistralModel } from "./models.service.js";
import {createAgent,providerStrategy} from 'langchain'

const State = new StateSchema({
  problem: z.string().default(""),
  solution_1: z.string().default(""),
  solution_2: z.string().default(""),
  judge: z.object({
        solution_1_score: z.number().int().min(1).max(10).default(1),
        solution_2_score: z.number().int().min(1).max(10).default(1),
        solution_1_reasoning: z.string().default(""),
        solution_2_reasoning: z.string().default(""),
      })
});

const solutionNode: GraphNode<typeof State> = async (state) => {

    const[mistralResponse,cohereResponse] = await Promise.all([
        mistralModel.invoke(state.problem),
        cohereModel.invoke(state.problem)
    ])
  return{
    solution_1: mistralResponse.text,
    solution_2: cohereResponse.text
  }
};

const judgeNode: GraphNode<typeof State> = async (state) =>{
    console.log("invoking judge with state", state)
    const {problem,solution_1,solution_2} = state;

    const judge = createAgent({
        model: geminiModel,
        tools: [],
        responseFormat: providerStrategy(z.object({
            solution_1_score: z.number().int().min(1).max(10),
            solution_2_score: z.number().int().min(1).max(10),
            solution_1_reasoning: z.string(),
            solution_2_reasoning: z.string(),
        })),
        systemPrompt: `You are the judge tasked with evaluating two solutions generated by different AI models.
        Give each solution one whole-number score from 1 to 10, where 10 is exceptional and 1 is unusable.
        Explain the score clearly, considering correctness, completeness, clarity, and practical usefulness.`
    })

    const judgeResponse = await judge.invoke({
        messages: [
            new HumanMessage(`
              Problem: ${problem}
              Solution 1: ${solution_1}
              Solution 2: ${solution_2}
              Please evaluate both solutions independently. Return a whole-number score from 1 to 10 and concise reasoning for each.
            `)
        ]
    })
    const {
      solution_1_score,
      solution_2_score,
      solution_1_reasoning,
      solution_2_reasoning,
    } = judgeResponse.structuredResponse

    return{
        judge:{
          solution_1_score,
          solution_2_score,
          solution_1_reasoning,
          solution_2_reasoning,
        }
    }
}


const graph = new StateGraph(State)
  .addNode("solution", solutionNode)
  .addNode("judge_node",judgeNode)
  .addEdge(START, "solution")
  .addEdge("solution","judge_node")
  .addEdge("judge_node",END)
  .compile();


export default async function (problem: string) {
    const result = await graph.invoke({ 
       problem:problem
    })
    console.log(result)
    return result

}





// type JUDGEMENT ={
//     winner: "solution_1" | "solution_2";
//     solution_1_score: number;
//     solution_2_score: number;
// }

// type AIBATTLESTATE = {
//     messages: typeof MessagesValue;
//     solution_1:string;
//     solution_2:string;
//     judgement:JUDGEMENT; 
// }

// const state: AIBATTLESTATE={
//     messages: MessagesValue,
//     solution_1: "",
//     solution_2: "",
//     judgement : {
//         winner: "solution_1",
//         solution_1_score: 0,
//         solution_2_score: 0
//     }
// }